[package]
name = "rusty-raft"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
log = "0.4"
env_logger = "0.11.8"
tokio = {version= "1.47.1", features = ["full"] }